version: '3.9'

services:
  langchain:
    container_name: langchain-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
    env_file:
      - .env
